### ISSUE TITLE
Image download error for IOS 15.1 or some other versions

### ISSUE THREAD

**Issue by astrozxwu** [yiguanxianyu/PKUAutoRun#1]
https://raw.fastgit.org/filsv/iPhoneOSDeviceSupport/master/
上IOS版本好像不太全；比如比较新的IOS缺少镜像；
我在
https://github.com/filsv/iPhoneOSDeviceSupport
下载，运行正常已经开跑了x

**Comment by yiguanxianyu** [comment]
收到，现在好像没有稳定可用的镜像，Github 本身在墙内也容易抽风，我也蹲一个好的解决方案x

**Comment by yiguanxianyu** [comment]
刚才看了一眼，是因为15.1命名不标准导致的，我修改了一下下载的链接。镜像本身还活着，还能再苟一会x
