### ISSUE TITLE
iOS 17运行报错，可能和新的镜像有关

### ISSUE THREAD

**Issue by En-tropy** [yiguanxianyu/PKUAutoRun#12]
运行main.py会显示：

开始下载模拟所需的开发者镜像文件
···镜像文件已存在
···镜像签名文件已存在
command ReceiveBytes failed to send bytes with: {'DetailedError': 'Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to create path with signature {length = 14, bytes = 0x3430343a204e6f7420466f756e64} in (null)." UserInfo={NSLocalizedDescription=Failed to create path with signature {length = 14, bytes = 0x3430343a204e6f7420466f756e64} in (null).}', 'Error': 'InternalError', 'Status': 'ReceiveBytesAck'}

好像新系统的镜像文件机制有更新？

**Comment by yiguanxianyu** [comment]
iOS17机制有大改，但是我现在手上没有设备调试不了了，所以只能等有缘人接手了
