### ISSUE TITLE
目前确认能够跑起来的iPhone型号

### ISSUE THREAD

**Issue by RayuelaShen** [yiguanxianyu/PKUAutoRun#16]
### ios17+ 用户也想AutoRun

很可惜, 新款果子手机无法 `AutoRun`. 在不越狱的情况下, 目前一种可行的解决方法是掏一台老苹果手机. 如果苹果在 `ios17` 更新时放弃了该型号的支持, 那该型号的手机就可以合法的保持在 `ios16` 或更早的版本, 这台手机就满足 `AutoRun` 的设备要求.
根据调研, 目前满足这一要求的手机型号范围是 `iPhone 6S - iPhone X`. 具体可以参照 https://ipsw.me/ 提供的 `Signed` 的最终固件版本. 如果你的老手机系统过于老旧以至于无法正常使用 PKURunner, 也可以从该网站上下载相应固件, 借助 iTunes 等软件刷机使用. (是时候把家里积灰尘的老水果掏出来了!!!)(iPhone 6或更早的型号只能更新到 ios12, 能否正常使用 PKURunner 未知)

**Comment by yiguanxianyu** [comment]
毕业一年半了，我都想知道这个项目还能用不😢

**Comment by RayuelaShen** [comment]
实测可用, 但是还是老样子不支持IOS17+, 不支持步数, 安装的时候一些库得downgrade才能用
