### ISSUE TITLE
请问现在支持ios16吗?

### ISSUE THREAD

**Issue by tobornotxx** [yiguanxianyu/PKUAutoRun#5]
IOS16下载镜像时python报错

**Comment by yiguanxianyu** [comment]
应该是加速源挂了，把image.py里面的 base_url 临时改成下面这个试试
https://fastly.jsdelivr.net/gh/pdso/DeveloperDiskImage@master/{}/DeveloperDiskImage.dmg

**Comment by tobornotxx** [comment]
> 应该是加速源挂了，把image.py里面的 base_url 临时改成下面这个试试 [https://fastly.jsdelivr.net/gh/pdso/DeveloperDiskImage@master/{}/DeveloperDiskImage.dmg](https://fastly.jsdelivr.net/gh/pdso/DeveloperDiskImage@master/%7B%7D/DeveloperDiskImage.dmg)

我改了之后在python里运行显示“urllib.error.HTTPError: HTTP Error 400: Bad Request”，但是自己访问网址是能下载下来的，这该怎么办呢？

**Comment by yiguanxianyu** [comment]
我刚才试了一下，现在提供给你几个方案你试一下：

 1. 手动在项目文件夹下创建 `Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/你的iOS版本` 文件夹（/表示目录层级），然后把dmg和dmg.signature文件拷贝进去，注意文件名（参考image.py）
 2. 使用 `https://js.cdn.haah.net/gh/pdso/DeveloperDiskImage@master/{}/DeveloperDiskImage.dmg` ，这个我测试可以用 `wget` 下载
 3. 用 `requests` 库下载，需要安装这个库并且自行 import：
     ```python
    import requests
    img = requests.get(img_url, allow_redirects=True)
    open(img_dir, 'wb').write(img.content)
    sig = requests.get(sig_url, allow_redirects=True)
    open(sig_dir, 'wb').write(sig.content)
    ```
欢迎进一步反馈

**Comment by tobornotxx** [comment]
> 

第一種方法解決了 感謝

**Comment by yiguanxianyu** [comment]
我刚才查看了相关资料，程序运行需要打开开发者模式，但在 iOS 16 中，打开开发者模式需要先解除手机密码，否则将会无法使用，如果你后续遇到问题可以参考。

**Comment by yiguanxianyu** [comment]
已经更新了对iOS16对支持，烦请测试

**Comment by tobornotxx** [comment]
> 
目前使用是正常的，我是用爱思助手打开的开发者模式，运行是正常的
