### ISSUE TITLE
镜像解压缩后报错

### ISSUE THREAD

**Issue by cyanmaple233** [yiguanxianyu/PKUAutoRun#6]
很长的一段报错，raise PyMobileDevice3Exception(f'command MountImage failed with: {result}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: command MountImage failed with: {'DetailedError': 'Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to mount /private/var/run/mobile_image_mounter/745DF51C1CAEBF3AF78F9B81AC8DB49514B54A6D1CDA2D134BC2EC86F91E9DCAB0BF8E5B3E388318DD3947F40C8F0D9110480D633AC922D7C1B7B48943B7A057/C174AC2D6E5C9D22F9529D74E784A52DB749023D698B315A90D903E959628436B1B8E8AF7FCFBFBBE365EA1D039CBDB5EC1DABB781F0ED9778555B8843264968/aPs1VL.dmg." UserInfo={NSLocalizedDescription=Failed to mount /private/var/run/mobile_image_mounter/745DF51C1CAEBF3AF78F9B81AC8DB49514B54A6D1CDA2D134BC2EC86F91E9DCAB0BF8E5B3E388318DD3947F40C8F0D9110480D633AC922D7C1B7B48943B7A057/C174AC2D6E5C9D22F9529D74E784A52DB749023D698B315A90D903E959628436B1B8E8AF7FCFBFBBE365EA1D039CBDB5EC1DABB781F0ED9778555B8843264968/aPs1VL.dmg., NSUnderlyingError=0x145404270 {Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Invalid value for MountPath: Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to verify the disk image mount path /Developer." UserInfo={NSLocalizedDescription=Failed to verify the disk image mount path /Developer.}" UserInfo={NSLocalizedDescription=Invalid value for MountPath: Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to verify the disk image mount path /Developer." UserInfo={NSLocalizedDescription=Failed to verify the disk image mount path /Developer.}}}}', 'Error': 'ImageMountFailed'}

**Comment by yiguanxianyu** [comment]
补充一下系统环境，我晚上看一下

**Comment by cyanmaple233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你的来信已收到，我会很快给你回信。

**Comment by yiguanxianyu** [comment]
我刚才查看了相关资料，程序运行需要打开开发者模式，但在 iOS 16 中，打开开发者模式需要先解除手机密码，否则将会无法使用，如果你后续遇到问题可以参考。

**Comment by cyanmaple233** [comment]
好的，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月25日(周二) 晚上11:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yiguanxianyu/PKUAutoRun] 镜像解压缩后报错 (Issue #6)

**Comment by yiguanxianyu** [comment]
已经更新了对iOS16对支持，烦请测试

**Comment by cyanmaple233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你的来信已收到，我会很快给你回信。
