### ISSUE TITLE
运行时出现错误TypeError: Can't instantiate abstract class

### ISSUE THREAD

**Issue by EmptyBlueBox** [yiguanxianyu/PKUAutoRun#8]
报错信息：
PKUAutoRun v1.2.1
提示: 如果要使用多台设备同时打卡, 请多开本程序
请输入跑步里程(米), 如5公里输入5000: 5000
请输入你希望的平均配速(秒), 如五分配速输入300: 300
Traceback (most recent call last):
  File "/Users/*/Documents/GitHub/PKUAutoRun/main.py", line 128, in <module>
    main(_distance, _speed)
  File "/Users/*/Documents/GitHub/PKUAutoRun/main.py", line 46, in main
    device_lockdown_client = LockdownClient(device.serial)
TypeError: Can't instantiate abstract class LockdownClient with abstract method _create_service_connection

**Comment by zhuozhiyongde** [comment]
pymobiledevice3 已更新至 2.0 版本，降级即可
pip install pymobiledevice3==1.42.4
